import { useI18n } from '@/lib/i18n';

const copy = {
  fr: ['Mot de passe oublié ?', 'Réinitialiser mon mot de passe', 'Saisis l’adresse e-mail de ton compte.', 'Adresse e-mail', 'Envoyer le lien', 'Si un compte existe avec cette adresse, un lien a été envoyé. Vérifie aussi les indésirables.', 'Choisir un nouveau mot de passe', 'Nouveau mot de passe (6 caractères minimum)', 'Confirmer le mot de passe', 'Enregistrer mon mot de passe', 'Mot de passe modifié. Tu peux accéder à tes billets.', 'Accéder à mes billets', 'Retour à la connexion', 'Saisis une adresse e-mail valide.', 'Les mots de passe doivent être identiques et contenir au moins 6 caractères.', 'Lien invalide ou expiré. Demande un nouveau lien.', 'Impossible de terminer. Réessaie dans un instant.', 'Patiente une minute avant de demander un autre lien.'],
  en: ['Forgot password?', 'Reset my password', 'Enter your account email address.', 'Email address', 'Send reset link', 'If an account exists, a link has been sent. Check your spam folder too.', 'Choose a new password', 'New password (at least 6 characters)', 'Confirm password', 'Save password', 'Password updated. You can access your tickets.', 'Access my tickets', 'Back to sign in', 'Enter a valid email address.', 'Passwords must match and contain at least 6 characters.', 'Invalid or expired link. Request a new link.', 'Unable to complete. Please try again shortly.', 'Wait one minute before requesting another link.'],
  de: ['Passwort vergessen?', 'Passwort zurücksetzen', 'Gib die E-Mail-Adresse deines Kontos ein.', 'E-Mail-Adresse', 'Link senden', 'Falls ein Konto existiert, wurde ein Link gesendet. Prüfe auch den Spam-Ordner.', 'Neues Passwort wählen', 'Neues Passwort (mindestens 6 Zeichen)', 'Passwort bestätigen', 'Passwort speichern', 'Passwort geändert. Du kannst deine Tickets öffnen.', 'Meine Tickets öffnen', 'Zur Anmeldung', 'Gib eine gültige E-Mail-Adresse ein.', 'Die Passwörter müssen übereinstimmen und mindestens 6 Zeichen enthalten.', 'Link ungültig oder abgelaufen. Fordere einen neuen Link an.', 'Vorgang fehlgeschlagen. Bitte versuche es gleich erneut.', 'Warte eine Minute, bevor du einen weiteren Link anforderst.'],
  es: ['¿Olvidaste tu contraseña?', 'Restablecer contraseña', 'Introduce el correo de tu cuenta.', 'Correo electrónico', 'Enviar enlace', 'Si existe una cuenta, se ha enviado un enlace. Revisa también el correo no deseado.', 'Elegir nueva contraseña', 'Nueva contraseña (mínimo 6 caracteres)', 'Confirmar contraseña', 'Guardar contraseña', 'Contraseña actualizada. Puedes acceder a tus entradas.', 'Ver mis entradas', 'Volver al inicio de sesión', 'Introduce un correo válido.', 'Las contraseñas deben coincidir y tener al menos 6 caracteres.', 'Enlace inválido o caducado. Solicita uno nuevo.', 'No se pudo completar. Inténtalo de nuevo en un momento.', 'Espera un minuto antes de solicitar otro enlace.'],
  it: ['Password dimenticata?', 'Reimposta password', 'Inserisci l’indirizzo e-mail del tuo account.', 'Indirizzo e-mail', 'Invia link', 'Se esiste un account, è stato inviato un link. Controlla anche lo spam.', 'Scegli una nuova password', 'Nuova password (almeno 6 caratteri)', 'Conferma password', 'Salva password', 'Password aggiornata. Puoi accedere ai tuoi biglietti.', 'Accedi ai miei biglietti', 'Torna al login', 'Inserisci un indirizzo e-mail valido.', 'Le password devono coincidere e contenere almeno 6 caratteri.', 'Link non valido o scaduto. Richiedi un nuovo link.', 'Impossibile completare. Riprova tra poco.', 'Attendi un minuto prima di richiedere un altro link.'],
  pt: ['Esqueceu a senha?', 'Redefinir senha', 'Insira o e-mail da sua conta.', 'E-mail', 'Enviar link', 'Se existir uma conta, um link foi enviado. Verifique também o spam.', 'Escolher nova senha', 'Nova senha (mínimo 6 caracteres)', 'Confirmar senha', 'Salvar senha', 'Senha atualizada. Você pode acessar seus ingressos.', 'Ver meus ingressos', 'Voltar ao login', 'Insira um e-mail válido.', 'As senhas devem ser iguais e ter pelo menos 6 caracteres.', 'Link inválido ou expirado. Solicite um novo link.', 'Não foi possível concluir. Tente novamente em instantes.', 'Aguarde um minuto antes de solicitar outro link.'],
  zh: ['忘记密码？', '重置密码', '请输入账户的电子邮箱。', '电子邮箱', '发送重置链接', '如果该邮箱存在账户，链接已发送。请同时检查垃圾邮件。', '设置新密码', '新密码（至少6个字符）', '确认密码', '保存密码', '密码已更新，可以查看门票。', '查看我的门票', '返回登录', '请输入有效的邮箱地址。', '密码必须一致且至少包含6个字符。', '链接无效或已过期，请重新申请。', '无法完成，请稍后重试。', '请等待一分钟后再申请链接。'],
  ko: ['비밀번호를 잊으셨나요?', '비밀번호 재설정', '계정의 이메일 주소를 입력하세요.', '이메일 주소', '링크 보내기', '계정이 있다면 링크가 전송되었습니다. 스팸함도 확인하세요.', '새 비밀번호 설정', '새 비밀번호 (6자 이상)', '비밀번호 확인', '비밀번호 저장', '비밀번호가 변경되었습니다. 티켓을 확인할 수 있습니다.', '내 티켓 보기', '로그인으로 돌아가기', '유효한 이메일 주소를 입력하세요.', '비밀번호는 동일해야 하며 6자 이상이어야 합니다.', '유효하지 않거나 만료된 링크입니다. 새 링크를 요청하세요.', '완료하지 못했습니다. 잠시 후 다시 시도하세요.', '새 링크를 요청하기 전에 1분 기다려 주세요.'],
  ja: ['パスワードを忘れましたか？', 'パスワードを再設定', 'アカウントのメールアドレスを入力してください。', 'メールアドレス', 'リンクを送信', 'アカウントが存在する場合、リンクを送信しました。迷惑メールも確認してください。', '新しいパスワードを設定', '新しいパスワード（6文字以上）', 'パスワードを確認', 'パスワードを保存', 'パスワードを変更しました。チケットを確認できます。', 'チケットを見る', 'ログインに戻る', '有効なメールアドレスを入力してください。', 'パスワードは一致し、6文字以上である必要があります。', 'リンクが無効または期限切れです。新しいリンクを申請してください。', '完了できませんでした。しばらくしてから再試行してください。', '新しいリンクを申請する前に1分お待ちください。'],
} as const;
const keys = ['forgot','requestTitle','requestSub','email','send','sent','newTitle','password','confirm','save','saved','tickets','back','invalidEmail','mismatch','expired','error','cooldown'] as const;
export function usePasswordResetText() {
  const { locale } = useI18n();
  const values = copy[locale.split('-')[0] as keyof typeof copy] ?? copy.en;
  return (key: typeof keys[number]) => values[keys.indexOf(key)];
}
