/**
 * Liste de pays (code ISO 2 lettres + nom FR). Le drapeau est dérivé du code.
 * Sélection large orientée scène street dance mondiale.
 */
export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'FR', name: 'France' },
  { code: 'BE', name: 'Belgique' },
  { code: 'CH', name: 'Suisse' },
  { code: 'GB', name: 'Royaume-Uni' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'IT', name: 'Italie' },
  { code: 'ES', name: 'Espagne' },
  { code: 'PT', name: 'Portugal' },
  { code: 'IE', name: 'Irlande' },
  { code: 'RO', name: 'Roumanie' },
  { code: 'PL', name: 'Pologne' },
  { code: 'CZ', name: 'Tchéquie' },
  { code: 'AT', name: 'Autriche' },
  { code: 'SE', name: 'Suède' },
  { code: 'NO', name: 'Norvège' },
  { code: 'DK', name: 'Danemark' },
  { code: 'FI', name: 'Finlande' },
  { code: 'GR', name: 'Grèce' },
  { code: 'HU', name: 'Hongrie' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'RU', name: 'Russie' },
  { code: 'TR', name: 'Turquie' },
  { code: 'US', name: 'États-Unis' },
  { code: 'CA', name: 'Canada' },
  { code: 'MX', name: 'Mexique' },
  { code: 'BR', name: 'Brésil' },
  { code: 'AR', name: 'Argentine' },
  { code: 'CL', name: 'Chili' },
  { code: 'CO', name: 'Colombie' },
  { code: 'JP', name: 'Japon' },
  { code: 'KR', name: 'Corée du Sud' },
  { code: 'CN', name: 'Chine' },
  { code: 'TW', name: 'Taïwan' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'TH', name: 'Thaïlande' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'PH', name: 'Philippines' },
  { code: 'ID', name: 'Indonésie' },
  { code: 'IN', name: 'Inde' },
  { code: 'AU', name: 'Australie' },
  { code: 'NZ', name: 'Nouvelle-Zélande' },
  { code: 'MA', name: 'Maroc' },
  { code: 'DZ', name: 'Algérie' },
  { code: 'TN', name: 'Tunisie' },
  { code: 'EG', name: 'Égypte' },
  { code: 'SN', name: 'Sénégal' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'CM', name: 'Cameroun' },
  { code: 'GH', name: 'Ghana' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'CD', name: 'RD Congo' },
  { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'AO', name: 'Angola' },
  { code: 'JM', name: 'Jamaïque' },
  { code: 'CU', name: 'Cuba' },
  { code: 'IL', name: 'Israël' },
  { code: 'LB', name: 'Liban' },
  { code: 'AE', name: 'Émirats arabes unis' },
];

export function countryName(code?: string | null): string {
  if (!code) return '';
  return COUNTRIES.find((c) => c.code === code.toUpperCase())?.name ?? code.toUpperCase();
}
